### PR TITLE
[BugFix] Fix message on reset password message for inactive user

### LINKED ISSUE #3950: Fix reset password message for inactive users
Users who are inactive get "Resent Password Link Sent to Email" message but do not receive emails.
We should not send them emails but at the same time show appropriate message here.
Screenshot 2023-04-28 at 2 42 43 PM

### PR DESCRIPTION
**Pull request by Suryansh5545**
Fixes #3950 

Current Behavior:-
Email send message is shown despite the email not being sent to the inactive user.

New Behavior:-
Message for account being inactive is shown and for account not existing as well.
AccountStatusMessage

### CODE REVIEW

File: frontend/src/js/controllers/authCtrl.js [hunk 1]
```diff
@@ -320,11 +320,16 @@
...
                         vm.isFormError = true;
-                        vm.FormError = "Something went wrong. Please try again";
+                        if (response.status === 400) {
+                            vm.FormError = response.data.details;
+                        } else {
+                            vm.FormError = "Something went wrong. Please try again";
+                        }
                         vm.stopLoader();
                     }
+
```
Comment (gchhablani) [inline frontend/src/js/controllers/authCtrl.js:332]: Remove this line.

File: frontend/tests/controllers-test/authCtrl.test.js [hunk 2]
```diff
@@ -322,7 +322,8 @@ describe('Unit tests for auth controller', function () {
                         }
                     });
                 } else {
-                    parameters.callback.onError();
+                    status = 400;
```
Comment (gchhablani) [inline frontend/tests/controllers-test/authCtrl.test.js:325]: Do we need to use a variable here?

**Review by gchhablani — COMMENTED** [review]
Pointed out some nits. Otherwise, looks good to me.

File: frontend/tests/controllers-test/authCtrl.test.js (hunk 2 above)
Comment (Suryansh5545) [reply frontend/tests/controllers-test/authCtrl.test.js]: variable is remove and status is given directly now

File: frontend/src/js/controllers/authCtrl.js [hunk 3]
```diff
@@ -320,9 +320,13 @@
                         vm.getUser.email = '';
                         vm.stopLoader();
                     },
-                    onError: function() {
+                    onError: function(response) {
                         vm.isFormError = true;
-                        vm.FormError = "Something went wrong. Please try again";
+                        if (response.status === 400) {
+                            vm.FormError = response.data.details;
+                        } else {
```
Comment (rahul2240) [inline frontend/src/js/controllers/authCtrl.js:327]: can go with a ternary operator here?

Comment (Suryansh5545) [reply frontend/src/js/controllers/authCtrl.js:327]: Done

Comment (rahul2240) [reply frontend/src/js/controllers/authCtrl.js:327]: Still seeing if else

File: frontend/tests/controllers-test/authCtrl.test.js [hunk 4]
```diff
@@ -309,8 +309,8 @@ describe('Unit tests for auth controller', function () {
     });
 
     describe('Unit tests for resetPassword function `auth/password/reset/`', function () {
-        var success;
-
+        var success, status;
```
Comment (gchhablani) [inline frontend/tests/controllers-test/authCtrl.test.js:312]: `status` is not being used anymore. Can remove this change.

File: frontend/src/js/controllers/authCtrl.js [hunk 5]
```diff
@@ -320,9 +320,9 @@
                         vm.getUser.email = '';
                         vm.stopLoader();
                     },
-                    onError: function() {
+                    onError: function(response) {
                         vm.isFormError = true;
-                        vm.FormError = "Something went wrong. Please try again";
+                        vm.FormError = (response.status == 400) ? response.data.details : "Something went wrong. Please try again";
```
Comment (gchhablani) [inline frontend/src/js/controllers/authCtrl.js:325]: Do all the errors from ValidationError have 400 status and will send `response.data.details`?

**Review by gchhablani — COMMENTED** [review]
Added some more comments.

File: frontend/src/js/controllers/authCtrl.js (hunk 5 above)
Comment (Suryansh5545) [reply frontend/src/js/controllers/authCtrl.js:325]: ValidationError sends the status 400 by default for bad request unless overridden. i have included a details message for both ValidationError so it will send it with all type of errors.

Comment (gchhablani) [reply frontend/src/js/controllers/authCtrl.js:325]: Basically, if any other arises, earlier we were just saying `Something went wrong. Please try again`, but now it will show the details for other errors as well (including Inactive Account)?

Comment (Suryansh5545) [reply frontend/src/js/controllers/authCtrl.js:325]: No it only covers if the account is inactive  or user doesn't exist, for other than these type of issues, it will resolve to something is  wrong message. if status code is not 200 or 400.

File: frontend/tests/controllers-test/authCtrl.test.js [hunk 6]
```diff
@@ -310,7 +310,7 @@ describe('Unit tests for auth controller', function () {
 
     describe('Unit tests for resetPassword function `auth/password/reset/`', function () {
         var success;
-
+        var inactivesms = 'Account is not active. Please contact the administrator.';
```
Comment (gautamjajoo) [inline frontend/tests/controllers-test/authCtrl.test.js:313]: a better variable name like `inactiveResponse`?

**Review by gchhablani — COMMENTED** [review]
LGTM!
